### PR TITLE
Add legacy filename support for jenv

### PR DESCRIPTION
**Pull request by carhartl**
So far I've been using jenv along with `.java-version` files, this would allow for migrating to asdf.

### CODE REVIEW

**Comment by halcyon** [comment]
@carhartl Thank you. I'm not familiar with `jenv`, but I'll become familiar with it and likely merge this within the next few days.

**Comment by carhartl** [comment]
Thanks!

=> http://www.jenv.be/

**Comment by halcyon** [comment]
I apologize for the delay - Thanksgiving holidays took more time from my schedule than I had anticipated. I've looked over both jenv and your changes and I don't quite understand the use case. Could you describe how you would use this in your workflow?

**Comment by carhartl** [comment]
Thanks, and no need to apologize! The use case is as follows: in my team we‘re using jenv to ensure a consistent environment for everyone, and thus each service/project has such a `.java-version` file. I‘ve migrated to asdf but I don‘t want to impose migrating on everyone else, and I also want to avoid maintaining an additional `.tool-versions` file just for me. Does that makes sense?

**Comment by carhartl** [comment]
Or did I overlook something?

**Comment by halcyon** [comment]
That sounds great. I wasn't able to find any documentation relating to the legacy filename feature in asdf-vm's docs. The best I could find was some mention of this feature in a few plugins (ruby and elixir). Their implementations were very similar to your own. I wanted to understand it better so I'd be able to support it. Your explanation was very helpful. Thanks again!

**Comment by carhartl** [comment]
I found a bit of explanation in the docs here: https://asdf-vm.com/#/core-configuration?id=homeasdfrc — but I also didn’t find it on my first attempt :)

Since I was so used to it from a variety of version managers (nodenv, rbenv, pyenv, ...) I forgot that not everyone might be, and missed to provide a better PR description.

Great that it is merged now, my migration to asdf is complete 🎉

**Pull request merged**
