### PR TITLE
Use BSD stat on macOS even if sha256sum is installed

### LINKED ISSUE #107: Strange output when installing a new version of java on MacOS
I just upgraded to the latest version of asdf-java and got this output when installing a new version of java

```
$ asdf install java adoptopenjdk-11.0.8+10
stat: cannot read file system information for '%c': No such file or directory
/Users/aconlin-oakley/.asdf/plugins/java/bin/install: line 49: ((: File: "/var/folders/lp/kqyc_xl960n9983b4r83d_tr0000gn/T//asdf-java.cache/releases.tsv"
    ID: 100000700000019 Namelen: ?       Type: apfs
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 122061322  Free: 7463614    Available: 2726592
Inodes: Total: 4882452880 Free: 4876245770 <= 1597269841 - 3600 : syntax error in expression (error token is ": "/var/folders/lp/kqyc_xl960n9983b4r83d_tr0000gn/T//asdf-java.cache/releases.tsv"
    ID: 100000700000019 Namelen: ?       Type: apfs
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 122061322  Free: 7463614    Available: 2726592
Inodes: Total: 4882452880 Free: 4876245770 <= 1597269841 - 3600 ")
#=#=-  #       #                                                                                                                                                                                                                                               #=O=#     #
  #                                                                                                                                                                                                                                           -#O=- #      #          #
######################################################################################################################################################################################################################################################### 100.0%-=O#-   #
 #           #                                                                                                                                                                                                                                  -=O=#      #         #
######################################################################################################################################################################################################################################################### 100.0%
OpenJDK11U-jdk_x64_mac_hotspot_11.0.8_10.tar.gz
OpenJDK11U-jdk_x64_mac_hotspot_11.0.8_10.tar.gz: OK
```

### PR DESCRIPTION
**Pull request by joschi**
Fixes #107

### CODE REVIEW

**Comment by bdellegrazie** [comment]
@halcyon any chance of getting this merged please? We're seeing the same issue on some of our developer's systems for exactly the same reason (gnu coreutils on MacOS path overriding BSD stat)

**Comment by halcyon** [comment]
Yes @bdellegrazie . Sorry about this falling through the cracks, I didn't see this. I'll review it now.

**Comment by halcyon** [comment]
After looking carefully on my mac, I'd like to understand more. Why is /usr/local/opt/coreutils/libexec/gnubin part of PATH? Is homebrew being used to install/manage coreutils?. This looks like it could be an environment configuration issue.

**Comment by bdellegrazie** [comment]
@halcyon Developers frequently install coreutils via brew and normally these are only visible on the path via their `g` prefix (e.g. `gstat`) however there is documentation on how to "replace" BSD utilities with their GNU equivalents to simplify some development focused activities. This is a matter of personal preference and relates to their specific use-case.

You're absolutely correct that its a configuration issue but it's also not something that can be easily worked around by the user without significant impact. The simplest solution, since we're expecting BSD type utilities is to explicitly specify the path which will ensure the correct behaviour.

An alternate option might be to get ASDF to expose common functions for these types of tools which can be overridden by a user who installs coreutils and maps it in the path. That would arguably solve this problem for all plugins but is substantially higher complexity.

**Comment by joschi** [comment]
@halcyon Anything we can do to move this PR forward?

**Pull request merged**
