### PR TITLE
Fix the error 'already ends with semicolon' causing by the misuse of export

### LINKED ISSUE #91: Error when PROMPT_COMMAND already ends with semicolon
When using [direnv](https://github.com/direnv/direnv) and `set-java-home.bash`, the `PROMPT_COMMAND` will be set to:

```bash
_direnv_hook;; prompt_command
```

This causes bash to cry, because it does not like `;;` :cry: 

```
-bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;;'
-bash: PROMPT_COMMAND: line 0: `_direnv_hook;; prompt_command'        
```

I thought of checking whether `PROMPT_COMMAND` already ends with `;` to avoid adding another `;`, but I am not a bash expert. Maybe there is a better way to solve this issue.

I am currently using this as a workaround:

```bash
export PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND} :}"

. ~/.asdf/plugins/java/set-java-home.sh
```

`PROMPT_COMMAND` will be set to `_direnv_hook; :; prompt_command`. See [this comment](https://stackoverflow.com/a/3224910/9858139) at Stackoverflow to understand what `:` stands for.

### PR DESCRIPTION
**Pull request by jinmiaoluo**
fixes #91

### CODE REVIEW

**Comment by halcyon** [comment]
LGTM. Any thoughts @joschi ?

**Review by joschi — APPROVED** [review]
@halcyon LGTM.

@jinmiaoluo Does this problem only exist in bash or should we update the other scripts too?

**Comment by jinmiaoluo** [comment]
> @halcyon LGTM.
> 
> @jinmiaoluo Does this problem only exist in bash or should we update the other scripts too?

Sorry @halcyon, I don't familiar with Zsh/Fish. If anyone is familiar with Zsh/Fish 'PROMPT_COMMAND' kind thing. Welcome to submit your merge request.

**Comment by joschi** [comment]
> Sorry @halcyon, I don't familiar with Zsh/Fish. If anyone is familiar with Zsh/Fish 'PROMPT_COMMAND' kind thing. Welcome to submit your merge request.

@jinmiaoluo That's fine. We can start with fixing the script for Bash. 😄

**Comment by halcyon** [comment]
Thank you!

**Pull request merged**
