### PR TITLE
Add Adopt OpenJDK 14

### PR DESCRIPTION
**Pull request by nicksen**

### CODE REVIEW

**Comment by austinbv** [comment]
I cannot reproduce the failing test locally 

Could we get this merged by any chance?

**Comment by nicksen** [comment]
Seems fine to me. Dunno why it would fail, I suppose the devs have a better understanding of things

**Comment by halcyon** [comment]
The failures are expected right now with Travis. My apologies for not getting this merged sooner - I think I got it confused with the Azul 14 pull. Thank you for the PR!

**Comment by nicksen** [comment]
Maybe I don't fully understand this thing, but I don't get why it would fail? If someone wants to explain it, I'll be more than happy to listen
No worries from me, just wanted to try it out at work and see what happens :smile:

**Pull request merged**
