### PR TITLE
Replace realpath occurrences with a custom function

### LINKED ISSUE #109: realpath on mac OS
when i put the script to change JAVA_HOME the console output this:
asdf_update_java_home:5: command not found: realpath

There are some similar issues about the use of realpath on Mac OS, in workaround i have installed coreutils with:
brew install coreutils

### PR DESCRIPTION
**Pull request by fcrespo82**
This pull request is aimed to fix #109 

I only updated the code on the `functions` file, we should change in the `set-java-home.*` files too. I just need to get your feedback if I should:

1. Create another file in another folder with the function to be sourced by the other files;
2. Create the function in every file that needs it;
3. Source the `functions` file on the other files where the function is needed.

My personal preference would be for the first option, but I leave it here for discussion.

### CODE REVIEW

**Comment by jlurena** [comment]
can this be merged?

**Comment by fcrespo82** [comment]
It is ready for review, and further discussion.

If the maintainers approve, yes, it can be merged.

**Review by joschi — APPROVED** [review]
LGTM.

**Comment by fcrespo82** [comment]
@joschi Just wait a sec... do not merge yet.  I forgot that we need to address if we should change in the `set-java-home.*` files too.

Look on the original PR text...

**Comment by fcrespo82** [comment]
Pinging @joschi and @halcyon. Which option should I follow?

**Comment by joschi** [comment]
@fcrespo82 Sorry for the late response!

I think it makes sense to update the `set-java-home.*` scripts too.

@halcyon What do you think?

**Comment by fcrespo82** [comment]
@joschi @halcyon Yes, I think it makes sense, but should I?

> 1. Create another file in another folder with the function to be sourced by the other files;
> 2. Create the function in every file that needs it;
> 3. Source the `functions` file on there other files where the function is needed.
> 
> My personal preference would be for the first option, but I leave it here for discussion.

**Comment by halcyon** [comment]
> @joschi @halcyon Yes, I think it makes sense too, but should I?
> 
> > 1. Create another file in another folder with the function to be sourced by the other files;
> > 2. Create the function in every file that needs it;
> > 3. Source the `functions` file on the other files where the function is needed.
> > 
> > My personal preference would be for the first option, but I leave it here for discussion.

I'm leaning towards options 2 and 3. 

- Option 3 seems the most sensible, but I can see how it could potentially result in performance issues on some platforms (like WSL2) that are performance sensitive (due to the defining of a bunch of functions that are never used).
- Option 2 has the lowest runtime overhead, but increases maintenance cost.
- Option 1 looks like it could be a good compromise but may add its own new issues around complexity and setting a precedent for adding new files when we add new functions.

**Comment by fcrespo82** [comment]
Hi folks, I went with the approach number 2 to get this out of the way.

If you find this should be changed, please let me know.

Thanks!

**Comment by halcyon** [comment]
Thank you @fcrespo82 . LGTM!

**Pull request merged**
